[github_action_config]
auto_review=true
auto_describe=true
auto_improve=true

[pr_reviewer]
extra_instructions="Please use Japanese."

[pr_description]
extra_instructions="Please use Japanese."

[pr_code_suggestions]
num_code_suggestions_per_chunk=4
