name: pr-agent

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PR Agent action step
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }} # Make sure to add your OpenAI key to your repo secrets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Make sure to add your GitHub token to your repo secrets
          github_action_config.auto_review: "false" # enable\disable auto review
          github_action_config.auto_describe: "true" # enable\disable auto describe
          github_action_config.auto_improve: "false" # enable\disable auto improve

          # PR_REVIEWER.EXTRA_INSTRUCTIONS: "Please use Japanese in descriptions."
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "Please use Japanese in descriptions."
          PR_DESCRIPTION.PUBLISH_LABELS: true

          CONFIG.ENABLE_CUSTOM_LABELS: true
          CUSTOM_LABELS.BUG.DESCRIPTION: "Use when PR Type is a 'Bug fix'"
          # CUSTOM_LABELS.enhancement.DESCRIPTION: "Adds new features or modifies existing ones"
          CUSTOM_LABELS.CHORE.DESCRIPTION: "Other changes that do not fit in any of the above categories"
